### ISSUE TITLE
Describe usage of this tool

### ISSUE THREAD

**Issue by mhhhkay** [shteou/helm-dependency-fetch#15]
Hey @shteou,
reading through your observations from https://stewartplatt.com/blog/speeding-up-helm-dependency-build/ i really see myself feeling the same pain.

However going through the readme of your tool I am missing some basic usage instructions.
Can you please expand your readme with the same?

highly appreciated.
Cheers

**Comment by shteou** [comment]
Hey @mhhhkay, does [this PR](https://github.com/shteou/helm-dependency-fetch/blob/09481f0850fcd7bf8f8b1dad9f2b5dfe17e144e4/README.md) look like it helps?

A word of warning, whilst this works for my simple use case it's not intended to be a production ready tool.
It falls far short of helm's configurability, so it would be nice to go back to the helm code and see if I can improve things there!

(And thanks for taking an interest, I hope it helps in some way 😄)

**Comment by mhhhkay** [comment]
Hey @shteou, thanks for the heads-up.
I think that will help in any way :-)

However I feel like it always requires a requirements.yaml
Due to helm v3 usage I have all dependencies stored within the Chart.yaml

As per your description "The tool reads dependencies from a Chart.yaml (API v2) file..." it would consider this file aswell.
Am I missing something out here?
Thanks.

PS: I ran this tool now in my dev stage (adjusted to requirements.yaml). 50 developers are praising it already. Fetch time reduced from 20 minutes!!! to 30 sec! \o/

**Comment by shteou** [comment]
Thanks @mhhhkay, added some more details to it. Happy helming!

**Comment by shteou** [comment]
fyi, I've just pushed #16 at version 1.0.0 which mirrors the `helm dependency build` command line
and adds usage/help to the command itself.

**Comment by mhhhkay** [comment]
Many thanks @shteou !
does this also include the dependency fetch from Chart.yaml ?
At least this is a major thing for me and pretty sure for others too.
I killed all requirements.yaml's when migrating to Helm v3.

**Comment by shteou** [comment]
> Many thanks @shteou ! does this also include the dependency fetch from Chart.yaml ? At least this is a major thing for me and pretty sure for others too. I killed all requirements.yaml's when migrating to Helm v3.

Yeah, it happily supports dependencies for either chart API 👍
It'll detect the chart type in `Chart.yaml`'s apiVersion field as Helm does.

Cheers!
